/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.ugr.cliente;

import java.awt.Color;


/**
 *
 * @author Usuario
 */
public class ClienteRedes extends javax.swing.JFrame {

    /**
     * Creates new form ClienteRedes
     * @param twitterUsername
     * @param instagramUsername
     */
    public ClienteRedes(String twitterUsername, String instagramUsername) {
        initComponents();
        
        String seguidoresTwi = ClienteREST.askServerFor("twitterFollowers",twitterUsername);
        String seguidoresIns = ClienteREST.askServerFor("instagramFollowers",instagramUsername);
        
        this.usuarioTwitter.setText(twitterUsername);
        this.seguidoresTwitter.setText(seguidoresTwi);
        this.seguidosTwitter.setText(ClienteREST.askServerFor("twitterFollowed",twitterUsername));
        this.privacidadTwitter.setText(ClienteREST.askServerFor("twitterPrivacy",twitterUsername));
        if (ClienteREST.askServerFor("twitterVerified",twitterUsername).equals("Verificado"))
            this.verificadoTwitter.setText("Si");
        else
            this.verificadoTwitter.setText("No");
        this.descripcionTwitter.setText(ClienteREST.askServerFor("twitterBiography",twitterUsername));   
        
        this.usuarioInstagram.setText(instagramUsername);
        this.seguidoresInstagram.setText(seguidoresIns);
        this.seguidosInstagram.setText(ClienteREST.askServerFor("instagramFollowed",instagramUsername));
        this.privacidadInstagram.setText(ClienteREST.askServerFor("instagramPrivacy",instagramUsername));
        if (ClienteREST.askServerFor("instagramVerified",instagramUsername).equals("Verificado"))
            this.verificadoInstagram.setText("Si");
        else
            this.verificadoInstagram.setText("No");
        this.descripcionInstagram.setText(ClienteREST.askServerFor("instagramBiography",instagramUsername)); 
        
        this.descripcionTwitter.setLineWrap(true);
        this.descripcionTwitter.setWrapStyleWord(true);
        this.descripcionInstagram.setLineWrap(true);
        this.descripcionInstagram.setWrapStyleWord(true);

        int total = Integer.parseInt(seguidoresTwi) + Integer.parseInt(seguidoresIns);
        double media = (total * 1.0) / 2.0;
        this.totalSeguidores.setText(Integer.toString(total));
        this.mediaSeguidores.setText(Double.toString(media));
        
        setDefaultCloseOperation(ClienteRedes.DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionTwitter = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        descripcionInstagram = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        seguidoresTwitter = new javax.swing.JLabel();
        privacidadTwitter = new javax.swing.JLabel();
        seguidosInstagram = new javax.swing.JLabel();
        seguidoresInstagram = new javax.swing.JLabel();
        seguidosTwitter = new javax.swing.JLabel();
        verificadoTwitter = new javax.swing.JLabel();
        verificadoInstagram = new javax.swing.JLabel();
        privacidadInstagram = new javax.swing.JLabel();
        usuarioTwitter = new javax.swing.JLabel();
        usuarioInstagram = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        totalSeguidores = new javax.swing.JLabel();
        mediaSeguidores = new javax.swing.JLabel();

        jLabel19.setText("jLabel19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Seguidores");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setText("Seguidos");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel3.setText("Privacidad");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel4.setText("Verificado");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel5.setText("Seguidos");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setText("Verificado");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel7.setText("Privacidad");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel8.setText("Seguidores");

        descripcionTwitter.setEditable(false);
        descripcionTwitter.setColumns(20);
        descripcionTwitter.setRows(5);
        jScrollPane1.setViewportView(descripcionTwitter);

        descripcionInstagram.setEditable(false);
        descripcionInstagram.setColumns(20);
        descripcionInstagram.setRows(5);
        jScrollPane2.setViewportView(descripcionInstagram);

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel9.setText("Descripcion");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel10.setText("Descripcion");

        jLabel11.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 36)); // NOI18N
        jLabel11.setText("Análisis de redes sociales");

        seguidoresTwitter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        seguidoresTwitter.setText("jLabel12");

        privacidadTwitter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        privacidadTwitter.setText("jLabel13");

        seguidosInstagram.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        seguidosInstagram.setText("jLabel14");

        seguidoresInstagram.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        seguidoresInstagram.setText("jLabel15");

        seguidosTwitter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        seguidosTwitter.setText("jLabel16");

        verificadoTwitter.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        verificadoTwitter.setText("jLabel17");

        verificadoInstagram.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        verificadoInstagram.setText("jLabel18");

        privacidadInstagram.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        privacidadInstagram.setText("jLabel20");

        usuarioTwitter.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        usuarioTwitter.setForeground(new java.awt.Color(0, 0, 255));
        usuarioTwitter.setText("jLabel12");

        usuarioInstagram.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        usuarioInstagram.setForeground(new java.awt.Color(204, 0, 204));
        usuarioInstagram.setText("jLabel12");

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel12.setText("Total de Seguidores");

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel13.setText("Media de seguidores");

        totalSeguidores.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        totalSeguidores.setText("jLabel14");

        mediaSeguidores.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        mediaSeguidores.setText("jLabel15");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seguidosTwitter)
                                    .addComponent(seguidoresTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(privacidadTwitter)
                                    .addComponent(verificadoTwitter))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(seguidosInstagram))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(seguidoresInstagram)))
                                        .addGap(31, 31, 31)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(privacidadInstagram, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(verificadoInstagram, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(usuarioTwitter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(usuarioInstagram)
                        .addGap(89, 89, 89))))
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mediaSeguidores)
                    .addComponent(totalSeguidores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel11)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioTwitter)
                    .addComponent(usuarioInstagram))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(seguidoresTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(seguidoresInstagram))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(seguidosTwitter)
                    .addComponent(seguidosInstagram))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(privacidadTwitter)
                    .addComponent(privacidadInstagram)
                    .addComponent(jLabel7))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verificadoTwitter)
                    .addComponent(jLabel4)
                    .addComponent(verificadoInstagram)
                    .addComponent(jLabel6))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(totalSeguidores))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(mediaSeguidores))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteRedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteRedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteRedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteRedes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ClienteRedes("aa","aa").setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea descripcionInstagram;
    private javax.swing.JTextArea descripcionTwitter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel mediaSeguidores;
    private javax.swing.JLabel privacidadInstagram;
    private javax.swing.JLabel privacidadTwitter;
    private javax.swing.JLabel seguidoresInstagram;
    private javax.swing.JLabel seguidoresTwitter;
    private javax.swing.JLabel seguidosInstagram;
    private javax.swing.JLabel seguidosTwitter;
    private javax.swing.JLabel totalSeguidores;
    private javax.swing.JLabel usuarioInstagram;
    private javax.swing.JLabel usuarioTwitter;
    private javax.swing.JLabel verificadoInstagram;
    private javax.swing.JLabel verificadoTwitter;
    // End of variables declaration//GEN-END:variables
}
